# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 100
  # Allow longer lines in code blocks
  code_blocks: false
  # Allow longer lines in tables
  tables: false

# MD033/no-inline-html - Allow some HTML in Markdown
MD033:
  allowed_elements:
    - br
    - details
    - summary

# MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041: false

# MD024/no-duplicate-heading/no-duplicate-header - Allow duplicate headings in different sections
MD024:
  allow_different_nesting: true
