repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-merge-conflict

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: ["--config", ".markdownlint.yaml"]

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [--fail-under=80, --verbose]
        exclude: ^(docs/|tests/|setup.py)

  - repo: local
    hooks:
      - id: check-docstring-first
        name: Check docstring is first
        entry: check-docstring-first
        language: python
        types: [python]

      - id: validate-docs-build
        name: Validate documentation build
        entry: mkdocs build --strict
        language: system
        files: \.(md|py|yml)$
        pass_filenames: false
