name: Documentation CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs-ci.yml'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -e ".[docs]"

    - name: Build documentation
      run: mkdocs build --strict

    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: documentation-site
        path: site/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'

    steps:
    - uses: actions/checkout@v4

    - name: Download documentation artifact
      uses: actions/download-artifact@v4
      with:
        name: documentation-site
        path: site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        publish_branch: gh-pages
        full_commit_message: "docs: update documentation site [skip ci]"
