name: services CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'services/**'
      - '.github/workflows/services-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/**'
      - '.github/workflows/services-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install Dependencies
      run: |
        cd services
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install colorama  # For docstring checker

    - name: Run Tests
      run: |
        cd services
        pytest --cov=app --cov-report=xml

    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./services/coverage.xml

    - name: Check Docstring Coverage
      run: |
        cd services
        python tools/check_docstrings.py --path app --threshold 80 --verbose

    - name: Run Security Scan
      run: |
        cd services
        pip install safety
        safety check

  docs:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Build documentation
        run: mkdocs build
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: ./services
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/syntelligence:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/syntelligence:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/syntelligence:latest
        cache-to: type=inline
